---
- hosts: app
  become: true

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create directory for app
      file:
        path: /home/chuck/app
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0755'

    - name: Copy /app contents
      copy:
        src: ../app/
        dest: /home/chuck/app/
        owner: "{{ ansible_user }}"


    - name: Create network
      shell: |
        docker network create chuck-net

    - name: Build and run application container
      shell: |
        cd /home/chuck/app
        docker build -t chuck-app .
        docker run -d --name app --network chuck-net chuck-app
        

    - name: Build and run Nginx container
      shell: |
        cd /home/chuck/app
        docker build -t nginx-proxy -f nginx.Dockerfile .
        docker run -d -p 80:80 --name nginx --network chuck-net nginx-proxy